### Test Load into audio, sr

In [57]:
import librosa as lb
import numpy as n
import soundfile as sf
from pathlib import Path

In [52]:
p = './pink.mp3'
audio , sr = lb.load(p, sr= None)

In [53]:
d = len(audio)/sr
print("Duration is : " ,d)
ch=audio[30*sr:50*sr]
sf.write("ch.wav",ch, sr)

Duration is :  230.57414965986393


In [54]:
audio.max()

np.float32(0.917444)

In [55]:
a = n.full((2, 20) , 2)
b = n.full((1, 10) , 3)
a, b

(array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]),
 array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]))

In [56]:
a

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

### Function Creation

#### Goal
split into 3+ sec overlapped chunks
Domain
Original ============================
domain   ==+======================+==


In [26]:
def split( y, sr, min = 3 , max = 10 , n_chunks = 5):
    """
    Splits a signal into n_chunks of random length between min and max
    """
    chunks = []
    out = {}
    for i in range(n_chunks):
        start = n.random.randint(0, len(y) - sr * max)
        end = start + n.random.randint(sr * min, sr * max)
        chunks.append(y[start:end])
        out[i] = (start, end)
    print("Chunks:", chunks)
    print("Out:", out)
    return chunks , out

In [10]:
def y2wav(y, sr, path='chunk.wav'):
    """
    Saves a signal as a wav file
    """
    sf.write(path, y, sr)
    return path

In [11]:
for i in range(5):
    y = split(audio, sr, 3, 10, 5)
    for j in range(len(y)):
        y2wav(y[j], sr, f'chunk_{i}_{j}.wav')
        print(f'chunk_{i}_{j}.wav')

chunk_0_0.wav
chunk_0_1.wav
chunk_0_2.wav
chunk_0_3.wav
chunk_0_4.wav
chunk_1_0.wav
chunk_1_1.wav
chunk_1_2.wav
chunk_1_3.wav
chunk_1_4.wav
chunk_2_0.wav
chunk_2_1.wav
chunk_2_2.wav
chunk_2_3.wav
chunk_2_4.wav
chunk_3_0.wav
chunk_3_1.wav
chunk_3_2.wav
chunk_3_3.wav
chunk_3_4.wav
chunk_4_0.wav
chunk_4_1.wav
chunk_4_2.wav
chunk_4_3.wav
chunk_4_4.wav


In [12]:
def remove_wav_files():
    """
    Removes all wav files in the current directory and its subdirectories
    """
    import os
    for root, dir, files in os.walk('./'):
        for file in files:
            if file.endswith('.wav') & file.startswith('chunk_'):
                print(os.path.join(root, file))
                os.remove(os.path.join(root, file))

In [13]:
remove_wav_files()

./chunk_1_2.wav
./chunk_3_0.wav
./chunk_3_1.wav
./chunk_1_3.wav
./chunk_1_1.wav
./chunk_3_3.wav
./chunk_3_2.wav
./chunk_1_0.wav
./chunk_1_4.wav
./chunk_3_4.wav
./chunk_2_3.wav
./chunk_0_1.wav
./chunk_4_4.wav
./chunk_0_0.wav
./chunk_2_2.wav
./chunk_2_0.wav
./chunk_0_2.wav
./chunk_0_3.wav
./chunk_2_1.wav
./chunk_4_3.wav
./chunk_4_2.wav
./chunk_2_4.wav
./chunk_0_4.wav
./chunk_4_0.wav
./chunk_4_1.wav


In [29]:
a, b = split(audio, sr)  # Unpack the returned values
a  # Display the chunks list

Chunks: [array([-0.04389122, -0.04804954, -0.0509458 , ...,  0.10755384,
        0.11641155,  0.12578052], dtype=float32), array([-0.00262619, -0.01355862, -0.01877853, ...,  0.14296868,
        0.12883559,  0.11888561], dtype=float32), array([-0.05094646, -0.06125657, -0.07110847, ...,  0.04197299,
        0.03403009,  0.03170736], dtype=float32), array([ 0.04357758,  0.04060906,  0.03834049, ..., -0.09616322,
       -0.09254937, -0.09060371], dtype=float32), array([-0.03836041, -0.03263124, -0.01709021, ..., -0.1342293 ,
       -0.17826857, -0.19649264], dtype=float32)]
Out: {0: (486391, 813587), 1: (9106992, 9383763), 2: (2548155, 2704394), 3: (885481, 1096865), 4: (6431756, 6846617)}


[array([-0.04389122, -0.04804954, -0.0509458 , ...,  0.10755384,
         0.11641155,  0.12578052], dtype=float32),
 array([-0.00262619, -0.01355862, -0.01877853, ...,  0.14296868,
         0.12883559,  0.11888561], dtype=float32),
 array([-0.05094646, -0.06125657, -0.07110847, ...,  0.04197299,
         0.03403009,  0.03170736], dtype=float32),
 array([ 0.04357758,  0.04060906,  0.03834049, ..., -0.09616322,
        -0.09254937, -0.09060371], dtype=float32),
 array([-0.03836041, -0.03263124, -0.01709021, ..., -0.1342293 ,
        -0.17826857, -0.19649264], dtype=float32)]

In [39]:
es = [[b[i][0] / sr, b[i][1] / sr] for i in range(len(b))]
es

[[11.029274376417234, 18.448684807256235],
 [206.50775510204082, 212.78374149659865],
 [57.781292517006804, 61.324126984126984],
 [20.078934240362813, 24.872222222222224],
 [145.84480725623584, 155.25208616780046]]

### Add effects to chunks

In [ ]:
def pitchify(y, sr, n_steps=1):
    """
    Changes the pitch of a signal by n_steps semitones
    """
    y = lb.effects.pitch_shift(y, sr, n_steps)
    return y
def time_stretch(y, rate=1.0):
    """
    Stretches a signal by a given rate
    """
    y = lb.effects.time_stretch(y, rate)
    return y
def noise(y, noise_factor=0.005):
    """
    Adds noise to a signal
    """
    noise = n.random.randn(len(y))
    y = y + noise_factor * noise
    return y

np.float32(-0.9298333)

In [ ]:

def ds_create(path: Path):
    files = [files for files in path.glob('*.wav') or path.glob('*.mp3')]
    if len(files) == 0:
        print("No files found")
        return
    print(f"Found {len(files)} files")
    label = {}

    for i, file in enumerate(files):
        # Out of 3 possible effects
        effects = ["pitchify", "time_stretch", "noise"]
        n_effects = n.random.randint(1, 4) ,list()
        effects = n.random.choice(effects, n_effects, replace=False)

        effects_file_names  = apply_effects(file, effects)

        label[file ] = {
            "Index" : i,
            "File" : file,
            "Effects" : effects,
            "Effect File Output/s" : effects_file_names
        }

np.int64(7301468)

In [214]:
import random as r

In [77]:
t = n.arange(1,11, dtype=n.int8)
t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [184]:
r.choices(t, k= 4)

[np.int8(2), np.int8(3), np.int8(9), np.int8(1)]

In [238]:
a=list(["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"])
r.choices(a, k=4)

['four', 'five', 'seven', 'six']

In [ ]:
effects = ["pitchify", "time_stretch", "noise"]
n_effects = n.random.randint(1, 4)
effects = n.random.choice(effects, n_effects, replace=False)
l={}
file = "ch.wav"
effect_file_names = apply_effects()
l[ file ] = {
    "Index" : i,
    "File" : file,
    "Effects" : effects,
    "Chunks": l,
}

In [246]:
l['ch.wav']['Effects']

array(['noise', 'time_stretch', 'pitchify'], dtype='<U12')

In [ ]:
def save_chunks(y, sr , m_file, path='chunks/' ):
    """
    Saves chunks of a signal as wav files
    """
    chunk_paths = {}
    if not Path(path).exists():
        Path(path).mkdir(parents=True, exist_ok=True)
    for i, chunk in enumerate(y):
        sf.write(f'{path}/{m_file}chunk_{i}.wav', chunk, sr)
        print(f'{m_file}chunk_{i}.wav')
        chunk_paths[i] = f'{path}/{m_file}_chunk_{i}.wav'
    return chunk_paths

In [ ]:
def apply_effects(y, effects, m_file):
    """
    Applies a list of effects to a signal for single original full track file
    """
    file_names = []
    for i, effect in enumerate(effects):
        m_file = f"{m_file}_{effect}_" if effect != None else None
        if effect == "pitchify":
            steps = n.random.uniform(-3,3)
            y = pitchify(y)
            name = f'{m_file}_effect_pitchify_{i}.wav'
            file_names.append(name)
            save_chunks(y, sr, name)
        elif effect == "time_stretch":
            rate = n.random.uniform(0.4, 2.5)
            y = time_stretch(y, rate)
            name = f'{m_file}_effect_time_{i}.wav'
            save_chunks(y, sr, name)
            file_names.append(name)
        elif effect == "noise":
            noise_factor = n.random.uniform(0.001, 0.01)
            y = noise(y, noise_factor)
            name = f'{m_file}_effect_noise_{i}.wav'
            save_chunks(y, sr, name)
            file_names.append(name)

    return file_names



In [247]:
noise = n.random.randn(len(y))
noise

array([ 0.31661403, -0.02217355, -0.13481525, -0.56541187, -1.21436748])